### PR TITLE
Added repos directory and .gitkeep

### PR DESCRIPTION
**Pull request by jswanbeck**
Adds an empty directory in which to store repositories to run on the screensaver.

### CODE REVIEW

**Comment by rubicks** [comment]
👍

**Comment by rubicks** [comment]
@jswanbeck, you want to merge this? You want me to?

**Comment by jswanbeck** [comment]
@rubicks, go for it -- let's say the reviewer merges the pull request (upon approval) unless there are conflicts.

**Comment by jswanbeck** [comment]
Okay screw it I'm merging it.

**Pull request merged**
